### ISSUE TITLE
Add Pgadmin4 in docker compose

### ISSUE THREAD

**Issue by eiacopini** [GeoNode/geonode#11414]
Hi I'm trying to add pgadmin4 to the docker-compose, so that pgadmin is on domain.cloud/pgadmin4
```
pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    depends_on:
     - geonode
     - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root

```

and added the location /pgadmin4 in geonode.conf (sites-enabled)

```
location /pgadmin4 {
       set $upstream pgadmin4:5050;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_pass http://$upstream/;
        proxy_redirect off;

}
```

I restarted nginx docker exec -it nginx4geonode nginx -s reload

I get a 502 Bad Gateway error if I try to reach domain.cloud/pgadmin4. The error is nginx connect() failed (111 connection refused) while connecting to upstream client xxxx server: domain.cloud request GET /pgadmin4 HTTP/1.1 upstream http://172.18.0.7:5050/pgadmin4 host: "domain.cloud"

Is it theoretically possible to add other services to take advantage of the postgres and nginx installation?

**Comment by giohappy** [comment]
>Is it theoretically possible to add other services to take advantage of the postgres and nginx installation?

Hi @eiacopini. Sure, it's a matter of configuring the additional services as you're doing.
I can only suggest to check whether port 5050 is actually exposed and if you can reach pgadmin4:5050 from inside the Nginx container (`ping pgadmin4:5050`).

However, I would invite you to ask inside the mailing-list, since this issue is not strictly related to GeoNode functionality. I hope you don't mind if I close it.

**Comment by eiacopini** [comment]
ok I write in mailing list and try your suggest. Thank you so much.

**Comment by Inogeo** [comment]
Hello,

Please try the following:

1. Edit the file [geonode.conf.envsubst](https://github.com/GeoNode/geonode/blob/master/scripts/docker/nginx/geonode.conf.envsubst) with the appropriate configuration
2. Run `docker-compose build geonode` after modification of the geonode.conf
3. Check the logs with `docker logs nginx4geonode`

Does it solves your problem ?

**Comment by eiacopini** [comment]
![Screenshot 2023-08-24 110040](https://github.com/GeoNode/geonode/assets/107869133/be81092b-0eed-4e05-b61e-84d4b38029c6)

This is the ping.
@Inogeo I tried but sadly no. same error

**Comment by giohappy** [comment]
@eiacopini have you tried exposing port 5050 and reach PgAdmin4 directly, withotu proxying through Nginx?

**Comment by eiacopini** [comment]
```
pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    depends_on:
     - geonode
     - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
   expose:
    - "5050"
```
Same problem, could the error be in the redirect to https?

**Comment by eiacopini** [comment]
I add in docker compose

expose:
  - "5050"

But if a try to reach domain.cloud:5050
 Connection failed

**Comment by chumano** [comment]
pgadmin4 run at port 80.
So, You should try this
`set $upstream pgadmin4:80;`

**Comment by eiacopini** [comment]
@chumano you are right!!! :)
This is the working configuration. Maybe it can be useful for someone else.
Thank you so much.


```
pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    depends_on:
     - geonode
     - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
     SCRIPT_NAME: /pgadmin4
    port:
      - "5050:80"
     expose:
      - "5050"
```

```
location /pgadmin4 {
       set $upstream pgadmin4:80;
      
        proxy_set_header X-Script-Name /pgadmin4
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_pass http://$upstream/;
        proxy_redirect off;

}
```
