### ISSUE TITLE
DJango container fails silently - Cannot deploy

### ISSUE THREAD

**Issue by darkbox** [GeoNode/geonode#12936]
I'm not able to deploy the full stack of geonode. Django container keeps restarting in a loop, I guess because *uwsgi fails silently*, but there is nothing in the logs to point out what is the problem.

Here is my stack file (Docker Swarm):
```
# SWARM STACK

x-common-django:
  &default-common-django
  image: geonode/geonode:4.4.1
  env_file:
      - stack.env
  volumes:
    - statics:/mnt/volumes/statics
    - geoserver-data-dir:/geoserver_data/data
    - backup-restore:/backup_restore
    - data:/data
    - tmp:/tmp
  depends_on:
    - db
  deploy:
    replicas: 1

services:

  django:
    << : *default-common-django
    environment:
      - IS_CELERY=False
    entrypoint: ["/usr/src/geonode/entrypoint.sh"]
    command: "uwsgi --ini /usr/src/geonode/uwsgi.ini"
    #command: "python3 manage.py runserver 0.0.0.0:8000"  # Avoid uWSGI for now
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - geonode-network

  celery:
    << : *default-common-django
    environment:
      - IS_CELERY=True
    entrypoint: ["/usr/src/geonode/entrypoint.sh"]
    command: "celery-cmd"
    deploy:
      replicas: 1
    networks:
      - geonode-network

  memcached:
    image: memcached:alpine
    env_file:
      - stack.env
    command: memcached ${MEMCACHED_OPTIONS}
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "11211"]
      interval: 30s
      timeout: 30s
      retries: 5
    deploy:
      replicas: 1
    networks:
      - geonode-network

  geonode:
    image: geonode/nginx:1.25.3-latest
    env_file:
      - stack.env
    environment:
      - RESOLVER=127.0.0.11
    ports:
      - ${HTTP_PORT-3080}:80
      - ${HTTPS_PORT-3443}:443
    volumes:
      - nginx-confd:/etc/nginx
      - nginx-certificates:/geonode-certificates
      - statics:/mnt/volumes/statics
    deploy:
      replicas: 1
    networks:
      - geonode-network

  letsencrypt:
    image: geonode/letsencrypt:2.6.0-latest
    env_file:
      - stack.env
    volumes:
      - nginx-certificates:/geonode-certificates
    deploy:
      replicas: 1
    networks:
      - geonode-network

  geoserver:
    image: geonode/geoserver:2.24.3-latest
    env_file:
      - stack.env
    ports:
      - "${GEOSERVER_LB_PORT:-8088}:8080"
    volumes:
      - statics:/mnt/volumes/statics
      - geoserver-data-dir:/geoserver_data/data
      - backup-restore:/backup_restore
      - data:/data
      - tmp:/tmp
    depends_on:
      - data-dir-conf
      - django
    healthcheck:
      test: ["CMD", "curl", "-m", "10", "--fail", "--silent", "--write-out", "HTTP CODE : %{http_code}\n", "--output", "/dev/null", "http://localhost:8080/geoserver/ows"]
      interval: 60s
      timeout: 10s
      retries: 2
    deploy:
      replicas: 1
    networks:
      - geonode-network

  data-dir-conf:
    image: geonode/geoserver_data:2.24.3-latest
    entrypoint: sleep infinity
    volumes:
      - geoserver-data-dir:/geoserver_data/data
    healthcheck:
      test: "ls -A '/geoserver_data/data' | wc -l"
    deploy:
      replicas: 1
    networks:
      - geonode-network

  db:
    image: geonode/postgis:15.3-latest
    command: postgres -c "max_connections=200"
    env_file:
      - stack.env
    volumes:
      - dbdata:/var/lib/postgresql/data
      - dbbackups:/pg_backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - geonode-network

  rabbitmq:
    image: rabbitmq:3-alpine
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    deploy:
      replicas: 1
    networks:
      - geonode-network

networks:
  geonode-network:
    driver: overlay

volumes:
  statics:
    driver: local
  nginx-confd:
    driver: local
  nginx-certificates:
    driver: local
  geoserver-data-dir:
    driver: local
  dbdata:
    driver: local
  dbbackups:
    driver: local
  backup-restore:
    driver: local
  data:
    driver: local
  tmp:
    driver: local
  rabbitmq:
    driver: local
```

And here are the last lines in django container logs (No migration errors, etc):
```
....
Found another file with the destination path 'lib/js/plugins/anchor/plugin.min.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.

Found another file with the destination path 'mapstorestyle/img/s2cloudless-s2cloudless.png'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.

0 static files copied to '/mnt/volumes/statics/static', 5009 unmodified.

statics tasks done

Executing UWSGI server uwsgi --ini /usr/src/geonode/uwsgi.ini for Production

-----------------------------------------------------

FINISHED DJANGO ENTRYPOINT --------------------------

-----------------------------------------------------

got command uwsgi --ini /usr/src/geonode/uwsgi.ini

[uWSGI] getting INI configuration from /usr/src/geonode/uwsgi.ini
```

The rest of containers are up and running and *nginx returns 502* since uwsgi does not start? If I change uwsgi with python dev server geonode starts and do not reset, but the frontend has issues and obviously using the python server is not a good idea, but shows that must be something wrong with uwsgi.

**Comment by darkbox** [comment]
Update: I manage to start geonode with a hack. But I don't understand why I have to do this.

First, I modify the stack file django container:
```yml
django:
    << : *default-common-django
    environment:
      - IS_CELERY=False
    entrypoint: ["/usr/src/geonode/entrypoint.sh"]
    #command: "uwsgi --ini /usr/src/geonode/uwsgi.ini"
    command: "python3 manage.py runserver 0.0.0.0:8010" # <--- Add this dummy process to avoid the container to restart
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://localhost:8010/"] # <-- just so is marked as healthy
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - geonode-network
```

Start the stack, wait till is up and running, once is done open a shell and execute manually the command to start the web server `uwsgi --ini /usr/src/geonode/uwsgi.ini` and it works!

So if this works, why I need to do this hacky thing? The problem with this "solution" is that I have to manually intervene.
