### ISSUE TITLE
Memcached container not starting upon reboot

### ISSUE THREAD

**Issue by patoche71** [GeoNode/geonode#13262]
## Expected Behavior

All containers up and running upon reboot

## Actual Behavior

memcached container not started, causing unhealthy status of django4geonode container and Error 502 on Nginx. 
Starting manually memcached and restarting django4geonode container solved everything

## Steps to Reproduce the Problem

  1. Docker install of Geonode
  2.Check containers running upon installation
  3.Reboot to check missing container

## Specifications

  - GeoNode version: latest one as of June 13th, 2025
  - Installation type (vanilla, geonode-project): vanilla, docker
  - Installation method (manual, docker): docker
  - Platform: Ubuntu LTS 22.05
  - Additional details:

**Comment by mattiagiupponi** [comment]
The container for memcached, has a policy of  `restart: on-failure` and not like the others `restart: unless-stopped`
I guess this was done since memcached is not mandatory but needs to be manually activated in the .env file to make it work with GeoNode.
Please try to change the dockerfile like this for the memcached service:

```
memcached:
    image: memcached:alpine
    container_name: memcached4${COMPOSE_PROJECT_NAME}
    command: memcached ${MEMCACHED_OPTIONS}
    restart: unless-stopped
    healthcheck:
      test: nc -z 127.0.0.1 11211
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
```
