### ISSUE TITLE
Warnings at server runtime after migration to Django 1.8

### ISSUE THREAD

**Issue by sarasafavi** [GeoNode/geonode#2501]
Django's new system checks (https://docs.djangoproject.com/en/1.8/ref/checks/) generate a handful of warnings at runtime:

```
WARNINGS:
account.EmailConfirmation.created: (fields.W161) Fixed default value provided.
        HINT: It seems you set a fixed date / time / datetime value as default for this field. This may not be what you want. If you want to have the current date as default, use `django.utils.timezone.now`
base.ResourceBase.regions: (fields.W340) null has no effect on ManyToManyField.
dialogos.Comment.ip_address: (fields.W900) IPAddressField has been deprecated. Support for it (except in historical migrations) will be removed in Django 1.9.
        HINT: Use GenericIPAddressField instead.
services.WebServiceHarvestLayersJob.service: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
```

I'm currently working on these... Resolving will affect deps as well as GeoNode core; creating this issue to aggregate PR links once they are completed.
