### ISSUE TITLE
Celery_app typing error on docker-compose

### ISSUE THREAD

**Issue by waybarrios** [GeoNode/geonode#2682]
Please! Fix it Celery service on docker-compose:

Correct way: 

```

celery:
    image: geonode/django
    links:
      - rabbitmq
      - postgres
      - elasticsearch
    command: celery worker --app=geonode.celery_app:app -B -l INFO
```

Instead of: 

```

celery:
    image: geonode/django
    links:
      - rabbitmq
      - postgres
      - elasticsearch
    command: celery worker --app=geonode.celeryapp:app -B -l INFO
```
