### ISSUE TITLE
Download Layer Modal Improvements

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2795]
The links in the download layer modal are currently grouped in tabs by "images" and then "data", which is determined by whether they are `wms/gwc` services or not.  See: https://github.com/GeoNode/geonode/blob/master/geonode/layers/views.py#L334.

In regards to UX, many/most GeoNodes are data portals, so the data tab should probably come before "images" tab.  Some instances are primarily used for just shapefiles.  However, a more elegant solution would be to add some customization to the modal without requiring custom templates or code that can quickly fall out of date.  Maybe we could add a `DOWNLOAD_LAYOUT_DATA` array of tabs to the settings.  The links would then be mapped to this layout.  For example:

```python
DOWNLOAD_LAYOUT_DATA = [ ... ]
# or 
DOWNLOAD_LAYOUT_DATA = yaml.load(...)
```

```yaml
DOWNLOAD_LAYOUT_DATA:
  - label: Data
    links:
      - 'Zipped Shapefile'
      - 'GeoJSON'
  - label: Images
    links:
      - 'JPEG'
```

![image](https://cloud.githubusercontent.com/assets/1438253/21595732/022c6978-d0e6-11e6-8884-597f420594e4.png)
