### ISSUE TITLE
After running "docker-compose up" geoserver, geonode, postgis and postgres are unavailable

### ISSUE THREAD

**Issue by markich** [GeoNode/geonode#3676]
We are trying to have a fully functional Geonode instance and after successfully installing **Docker**  on a _**Ubuntu 16.04 LTS (Xenial)**_ we ran ```docker-compose up --build``` with the following updated/modified *"docker-compose.yml"* file:

```
version: '2.1'
services:

  db:
    image: geonode/postgis:9.6
    restart: unless-stopped
    container_name: db4${COMPOSE_PROJECT_NAME}
    stdin_open: true
    # tty: true
    labels:
        org.geonode.component: db
        org.geonode.instance.name: geonode
    volumes:
      - dbdata:/var/lib/postgresql/data
      - dbbackups:/pg_backups
    env_file:
      - ./scripts/docker/env/production/db.env

  elasticsearch:
    image: elasticsearch
    restart: unless-stopped
    container_name: elasticsearch4${COMPOSE_PROJECT_NAME}
    stdin_open: true
    # tty: true
    labels:
        org.geonode.component: elasticsearch
        org.geonode.instance.name: geonode

  rabbitmq:
    image: rabbitmq
    restart: unless-stopped
    container_name: rabbitmq4${COMPOSE_PROJECT_NAME}
    stdin_open: true
    # tty: true
    labels:
        org.geonode.component: rabbitmq
        org.geonode.instance.name: geonode

  django:
    restart: unless-stopped
    image: geonode/geonode:latest
    container_name: django4${COMPOSE_PROJECT_NAME}
    stdin_open: true
    # tty: true
    labels:
        org.geonode.component: django
        org.geonode.instance.name: geonode
    depends_on:
      - db
      - elasticsearch
      - rabbitmq
    command: django-admin.py runserver 0.0.0.0:8000 --settings=geonode.settings
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./scripts/docker/env/production/django.env

  celery:
    restart: unless-stopped
    image: geonode/geonode:latest
    container_name: celery4${COMPOSE_PROJECT_NAME}
    stdin_open: true
    # tty: true
    labels:
        org.geonode.component: celery
        org.geonode.instance.name: geonode
    depends_on:
      - db
      - elasticsearch
      - rabbitmq
    command: celery worker --app=geonode.celery_app:app -B -l INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./scripts/docker/env/production/celery.env

  consumers:
    image: geonode/geonode:latest
    restart: unless-stopped
    container_name: consumers4${COMPOSE_PROJECT_NAME}
    stdin_open: true
    # tty: true
    labels:
        org.geonode.component: consumers
        org.geonode.instance.name: geonode
    depends_on:
      - rabbitmq
      - db
      - elasticsearch
    command: python manage.py runmessaging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./scripts/docker/env/production/django.env

  geoserver:
    image: geonode/geoserver:2.12.x
    restart: unless-stopped
    container_name: geoserver4${COMPOSE_PROJECT_NAME}
    stdin_open: true
    # tty: true
    labels:
        org.geonode.component: geoserver
        org.geonode.instance.name: geonode
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - geoserver-data-dir:/geoserver_data/data
    env_file:
      - ./scripts/docker/env/production/geoserver.env

  geonode:
    image: geonode/nginx:geoserver
    restart: unless-stopped
    container_name: nginx4${COMPOSE_PROJECT_NAME}
    stdin_open: true
    # tty: true
    labels:
        org.geonode.component: nginx
        org.geonode.instance.name: geonode
    depends_on:
      - django
      - geoserver
    ports:
      - "8888:80"
    expose:
      - "80"

  data-dir-conf:
    image: geonode/geoserver_data:2.12.x
    restart: on-failure
    container_name: gsconf4${COMPOSE_PROJECT_NAME}
    labels:
        org.geonode.component: conf
        org.geonode.instance.name: geonode
    command: /bin/true
    volumes:
      - geoserver-data-dir:/geoserver_data/data

volumes:

  geoserver-data-dir:
    external: false
    name: ${COMPOSE_PROJECT_NAME}-gsdatadir
  dbdata:
    external: false
    name: ${COMPOSE_PROJECT_NAME}-dbdata
  dbbackups:
    external: false
    name: ${COMPOSE_PROJECT_NAME}-dbbackups
```
After a couple of test runs we have not been able to connect to **postgis**, neither to the **geoserver** admin page on `<server-ip-address>:8888/geoserver/web` nor the default **geonode** main page.

1st Run
=============================================
```
docker ps
docker exec -it db4geonode bash
psql -h <server-ip-address> -p 5432 -U postgres
```

2nd Run
=============================================
```
cd ./home/geonode/
docker-compose down
docker-compose up
docker ps
docker exec -it db4geonode bash
psql -h <server-ip-address> -p 5432 -U postgres
```

3rd Run
=============================================
```
cd ./home/geonode/
docker-compose down
docker-compose up
docker ps
docker exec -it db4geonode bash
su postgres
psql
CREATE DATABASE first_test_db;
psql -h <server-ip-address> -p 5432 -U postgres
\l
```
