### ISSUE TITLE
SPC Geonode uses Filestorage instead of PostGIS ingest if uploading a Layer

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#4354]
The docker setup for SPC Geonode will save the uploaded shapefile as file on the system, instead of ingesting it into the geodatabase datastore.

## expected behaviour:

The shapefile will get processed and a geometry enabled table created in the database geonode_data. Geoserver will read the table from the geonode_data PostGIS datastore.

## actual behaviour:

The shapefile will get processed and stored in the geoserver datadir as shapefile. Geoserver will serve the file through a shapefile datastore.

---

## current investigation:

SPC Geonode does not use the geonode/postgis-docker container but a plain [mdillon/postgis](https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/docker-compose.yml#L156) variant. Therefore the whole initializiation script [initdb-geonode.sh](
https://github.com/GeoNode/postgis-docker/blob/master/initdb-geonode.sh) will not be called. In there the geonode_data geodatabase is created. The tasks.py from [geonode/geonode-docker](https://github.com/GeoNode/geonode-docker/blob/master/tasks.py#L139-L160) is updating the database connection strings for the django db and geodata db and  *substituting* the variables in settings.py through `os.getenv()` calls. Later the variables will be used by geonode (the plain geonode repo - **not** the docker repo 'geonode-docker') entrypoint.sh to migrate and applying the fixtures.

SPC is using [initialize.py](https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/django/initialize.py) instead. The `GEODATABASE_URL` parameter will not be set.

I think this is the reason why GeoNode will 'just' upload the files to GeoServer-DataDir instead of ingesting them into a geodatabase.

## possible solution (TBD and tested)

Since settings.py will search for the env var `GEODATABASE_URL` we could just set it via compose variable. The current initialize.py has to be modified to create the geodatabase instance.

**Comment by gannebamm** [comment]
switching to geonode/postgis:10 and giving appropriate environment variables will result in seperate databases
```
  # PostGIS database.
  postgres:
    #image: mdillon/postgis:9.6-alpine # WIP against issue 4354 
    image: geonode/postgis:10
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GEONODE_DATABASE=${GEONODE_DATABASE}
      - GEONODE_DATABASE_PASSWORD=${GEONODE_DATABASE_PASSWORD}
      - GEONODE_GEODATABASE=${GEONODE_GEODATABASE}
      - GEONODE_GEODATABASE_PASSWORD=${GEONODE_GEODATABASE_PASSWORD}
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/${GEONODE_DATABASE}
      - GEODATABASE_URL=postgis://postgres:${POSTGRES_PASSWORD}@postgres:5432/${GEONODE_GEODATABASE}
    volumes:
      - /media/data/dockerdata/spc/db_data:/var/lib/postgresql/data/
    restart: on-failure
    stdin_open: true
    ports:
      - "5432:5432"
```

However some variables seem to be off or some init script is not running, which results in still uploading shapefiles as datastores, instead of ingesting them into postgis.

If anyone has a hint where the geonode/geonode datastore is created, I am happy to listen/read 👍
