### ISSUE TITLE
Implement API for compact permissions

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#9106]
```
Permissions will be managed according to a "compact" set:

 - view: view resource
 - download: view and download
 - edit: view download and edit (metadata, style, data)
 - manage: change permissions, delete resource, etc.

The GET method will return:

users:
 - username
 - first name
 - last name
 - permissions (view | download | edit | manage)

organizations:
 - title
 - name
 - permissions (view | download | edit | manage)

groups:
 - title
 - name
 - permissions (view | download | edit | manage)
```
