### ISSUE TITLE
How to install geonode the docker way +nginx reverse proxy?

### ISSUE THREAD

**Issue by fishfree** [GeoNode/geonode#9870]
There is already Nginx installed in my  server, I can't uninstall it. So I want to install geonode with Docker, only reverse proxy to public with Nginx.
This is my modifed docker-compose.yml:
```
version: '3.9'

# Common Django template for GeoNode and Celery services below
x-common-django:
  &default-common-django
  image: geonode/geonode:4.0
  restart: on-failure
  env_file:
    - .env
  volumes:
    # - '.:/usr/src/geonode'
    - /opt/geonode/statics:/mnt/volumes/statics
    - /opt/geonode/geoserver-data-dir:/geoserver_data/data
    - /opt/geonode/backup-restore:/backup_restore
    - /opt/geonode/data:/data
    - /opt/geonode/tmp:/tmp
  depends_on:
    db:
      condition: service_healthy
    geoserver:
      condition: service_healthy

services:

  # Our custom django application. It includes Geonode.
  django:
    << : *default-common-django
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: django4${COMPOSE_PROJECT_NAME}
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null http://127.0.0.1:8000/"
      start_period: 60s
      interval: 60s
      timeout: 10s
      retries: 10
    environment:
      - IS_CELERY=False
    entrypoint: ["/usr/src/geonode/entrypoint.sh"]
    command: "uwsgi --ini /usr/src/geonode/uwsgi.ini"

  # Celery worker that executes celery tasks created by Django.
  celery:
    << : *default-common-django
    image: geonode/geonode:4.0
    container_name: celery4${COMPOSE_PROJECT_NAME}
    depends_on:
      - django
    environment:
      - IS_CELERY=True
    entrypoint: ["/usr/src/geonode/entrypoint.sh"]
    command: "celery-cmd"

  # Geoserver backend
  geoserver:
    image: geonode/geoserver:2.20.5
    container_name: geoserver4${COMPOSE_PROJECT_NAME}
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null http://127.0.0.1:8080/geoserver/rest/workspaces/geonode.html"
      start_period: 60s
      interval: 60s
      timeout: 10s
      retries: 10
    env_file:
      - .env
    volumes:
      - statics:/mnt/volumes/statics
      - geoserver-data-dir:/geoserver_data/data
      - backup-restore:/backup_restore
      - data:/data
      - tmp:/tmp
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      data-dir-conf:
        condition: service_healthy

  data-dir-conf:
    image: geonode/geoserver_data:2.20.5
    container_name: gsconf4${COMPOSE_PROJECT_NAME}
    entrypoint: sleep infinity
    volumes:
      - geoserver-data-dir:/geoserver_data/data
    restart: on-failure
    healthcheck:
      test: "ls -A '/geoserver_data/data' | wc -l"

  # PostGIS database.
  db:
    # use geonode official postgis 13 image
    image: geonode/postgis:13
    command: postgres -c "max_connections=${POSTGRESQL_MAX_CONNECTIONS}"
    container_name: db4${COMPOSE_PROJECT_NAME}
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
      - dbbackups:/pg_backups
    restart: on-failure
    healthcheck:
      test: "pg_isready -d gis"
    # uncomment to enable remote connections to postgres
    #ports:
    #  - "5432:5432"

  # Vanilla RabbitMQ service. This is needed by celery
  rabbitmq:
    image: rabbitmq:3.7-alpine
    container_name: rabbitmq4${COMPOSE_PROJECT_NAME}
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: on-failure

volumes:
  statics:
    name: ${COMPOSE_PROJECT_NAME}-statics
  geoserver-data-dir:
    name: ${COMPOSE_PROJECT_NAME}-gsdatadir
  dbdata:
    name: ${COMPOSE_PROJECT_NAME}-dbdata
  dbbackups:
    name: ${COMPOSE_PROJECT_NAME}-dbbackups
  backup-restore:
    name: ${COMPOSE_PROJECT_NAME}-backup-restore
  data:
    name: ${COMPOSE_PROJECT_NAME}-data
  tmp:
    name: ${COMPOSE_PROJECT_NAME}-tmp
  rabbitmq:
    name: ${COMPOSE_PROJECT_NAME}-rabbitmq
```
My nginx file like [this](https://github.com/GeoNode/geonode/blob/master/scripts/docker/nginx/geonode.conf.envsubst).

**Comment by t-book** [comment]
The nginx conf is using the internal dns names like django:8000. To proxy from your host nginx you need to make sure to expose the port to your host:

https://github.com/GeoNode/geonode/blob/a313150954b15a4a3c42e3800b8f19d0fc883d7b/docker-compose.yml#L26-L41

```
    ports:
      - "localhost:8000:8000"
```

and then instead of django set localhost

https://github.com/GeoNode/geonode/blob/a313150954b15a4a3c42e3800b8f19d0fc883d7b/scripts/docker/nginx/geonode.conf.envsubst#L116

`set $upstream localhost:8000; `

you need to do the same for other proxies like geoserver.

**Comment by Inogeo** [comment]
If you do not wan to play with port exposure and reverse proxy parameters. You can use this solution. It requires that you can connect your PRIMARY NGINX reverse proxy to a docker network.

1.  disable port exposure for geonode's nginx4geonode service by commenting these lines. https://github.com/GeoNode/geonode/blob/a313150954b15a4a3c42e3800b8f19d0fc883d7b/docker-compose.yml#L67-L69
2. Create an external network `docker network create GEONODE_NETWORK` https://docs.docker.com/engine/reference/commandline/network_create/
4. Connect nginx4geonode to this network: docker network connect
6. Change the *.conf setting file of the primary NGINX reverse proxy to redirect to nginx4geonode service (use nginx4geonode as domain name)
8. Connect nginx4geonode  to this network `docker network connect PRIMARY_NGINX_CONTAINER_NAME`
9. Restart your main primary proxy to reload config `docker container restart PRIMARY_NGINX_CONTAINER_NAME`

**Comment by fishfree** [comment]
@Inogeo @t-book  Thank you very much! I tried a lot, however, still no luck. Would you pls share your working docker-compose.yml, .env and Nginx site conf?

**Comment by smallvalthoss** [comment]
> @fishfree
> 
> I managed to get it working with my traefik setup maybe it helps
> 
> ```yaml
> networks:
>   yourTraefikNetwork:
>     external: true
>     name: yourTraefikNetwork
>     
> geoserver:
>     image: geonode/geoserver:2.20.5
>     # ...
>     labels:
>       traefik.enable: true
>       traefik.app.frontend.rule: Host:${HTTP_HOST};Path:/geoserver
>       traefik.app.port: 8080 #internal port to be exposed on https://HTTP_HOST
>       traefik.docker.network: yourTraefikNetwork
>     networks:
>       - yourTraefikNetwork
>       - default # this is important, as all other containers that do not explicitly set networks will be part of the 'default' network
> 
> geonode:
>     image: geonode/nginx:4.0
>     # ...
>     labels:
>       traefik.enable: true
>       traefik.app.frontend.rule: Host:${HTTP_HOST}
>       traefik.app.port: 80 #internal port to be exposed on https://HTTP_HOST
>       traefik.docker.network: yourTraefikNetwork
>     networks:
>       - yourTraefikNetwork
>       - default # this is important, as all other containers that do not explicitly set networks will be part of the 'default' network
> ```
> 
> .env changes:
> 
> ```shell
> GEOSERVER_WEB_UI_LOCATION=https://your.domain.com/geoserver/
> GEOSERVER_PUBLIC_LOCATION=https://your.domain.com/geoserver/
> GEOSERVER_LOCATION=https://your.domain.com/geoserver/
> GEONODE_LB_HOST_IP=your.domain.com
> GEONODE_LB_PORT=80
> PUBLIC_PORT=443 # this is important to enable login to the geoserver
> HTTP_HOST=your.domain.com
> HTTPS_HOST= # this is important (but a bit counter intuitive) as traefik is taking care of https so the internal nginx only serves on 80
> ```

Would you mind sharing your full (w/o secrets) env and docker compose? I'm having trouble getting this to work with traefik, unless I bypass nginx completely. In which case it seems to only allow one thread connected at a time..

**Comment by gotjoshua** [comment]
> Would you mind

@smallvalthoss well I wouldn't mind, but my setup was born in 2022 and I haven't played with it much, nor updated it since.

What do you mean by one thread at a time? How did you test that?

**Comment by smallvalthoss** [comment]
@gotjoshua okay, i finally figured it out. It seemed I had some broken links, I was finally able to get it working. Thank you for your help!

**Comment by ThomasBL-2** [comment]
> [@gotjoshua](https://github.com/gotjoshua) okay, i finally figured it out. It seemed I had some broken links, I was finally able to get it working. Thank you for your help!

Would you share your solution?

**Comment by smallvalthoss** [comment]
@ThomasBL-2 are you still looking for this?

**Comment by ThomasBL-2** [comment]
@smallvalthoss, yes, still. any help 'll be appreciated. something goes wrong with ports changing I guess

**Comment by smallvalthoss** [comment]
@ThomasBL-2 okay, here is my docker-compose.yml in full:

```yaml
networks:
  global:
    external: true
    name: global

# Common Django template for GeoNode and Celery services below
x-common-django:
  &default-common-django
  image: ${COMPOSE_PROJECT_NAME}/geonode:${GEONODE_BASE_IMAGE_VERSION}
  restart: unless-stopped
  env_file:
    - .env
  volumes:
    # - './src:/usr/src/wovx_geonode'
    - statics:/mnt/volumes/statics
    - geoserver-data-dir:/geoserver_data/data
    - backup-restore:/backup_restore
    - data:/data
    - tmp:/tmp
  depends_on:
    db:
      condition: service_healthy

services:

  # Our custom django application. It includes Geonode.
  django:
    << : *default-common-django
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: django4${COMPOSE_PROJECT_NAME}
    healthcheck:
      test: "curl -m 10 --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null http://django:8000/"
      start_period: 60s
      interval: 60s
      timeout: 10s
      retries: 2
    environment:
      - IS_CELERY=False
    entrypoint: ["/usr/src/wovx_geonode/entrypoint.sh"]
    command: "uwsgi --ini /usr/src/wovx_geonode/uwsgi.ini"
    networks:
      - default
      - global
    labels:
      - traefik.enable=true
      - traefik.http.routers.geonode.entrypoints=https
      - traefik.http.routers.geonode.rule=Host(`geonode.${DOMAIN}`)
      - traefik.http.routers.geonode.priority=1
      - traefik.http.routers.geonode.tls=true
      - traefik.http.services.geonode.loadbalancer.server.port=8000
      - traefik.docker.network=global

      - traefik.http.middlewares.geonode-cors.headers.accesscontrolallowmethods=GET,POST,PUT,PATCH,DELETE,HEAD,OPTIONS
      - traefik.http.middlewares.geonode-cors.headers.accesscontrolallowheaders=authorization
      - traefik.http.middlewares.geonode-cors.headers.accessControlAllowCredentials=true
      - traefik.http.middlewares.geonode-cors.headers.accesscontrolmaxage=100
      - traefik.http.middlewares.geonode-cors.headers.addvaryheader=true

      - traefik.http.routers.geonode.middlewares=geonode-cors

  # Celery worker that executes celery tasks created by Django.
  celery:
    << : *default-common-django
    container_name: celery4${COMPOSE_PROJECT_NAME}
    depends_on:
      django:
        condition: service_healthy
    environment:
      - IS_CELERY=True
    entrypoint: ["/usr/src/wovx_geonode/entrypoint.sh"]
    command: "celery-cmd"

  # Nginx is serving django static and media files and proxies to django and geonode
  # geonode:
  #   image: ${COMPOSE_PROJECT_NAME}/nginx:${NGINX_BASE_IMAGE_VERSION}
  #   build:
  #     context: ./docker/nginx
  #     dockerfile: Dockerfile
  #     args:
  #       - BASE_IMAGE_VERSION=${NGINX_BASE_IMAGE_VERSION}
  #   container_name: nginx4${COMPOSE_PROJECT_NAME}
  #   env_file:
  #     - .env
  #   environment:
  #     - RESOLVER=127.0.0.11
  #   ports:
  #     - "${HTTP_PORT}:80"
  #     - "${HTTPS_PORT}:443"
  #   volumes:
  #     - nginx-confd:/etc/nginx
  #     - nginx-certificates:/geonode-certificates
  #     - statics:/mnt/volumes/statics
  #   restart: unless-stopped

  # # memcached service
  # memcached:
  #   image: memcached:alpine
  #   container_name: memcached4${COMPOSE_PROJECT_NAME}
  #   command: memcached ${MEMCACHED_OPTIONS}
  #   restart: on-failure
  #   healthcheck:
  #     test: nc -z 127.0.0.1 11211
  #     interval: 30s
  #     timeout: 30s
  #     retries: 5
  #     start_period: 30s

  # Gets and installs letsencrypt certificates
#   letsencrypt:
#     image: ${COMPOSE_PROJECT_NAME}/letsencrypt:${LETSENCRYPT_BASE_IMAGE_VERSION}
#    build:
#      context: ./docker/letsencrypt
#      dockerfile: Dockerfile
#      args:
#        - BASE_IMAGE_VERSION=${LETSENCRYPT_BASE_IMAGE_VERSION}
#    container_name: letsencrypt4${COMPOSE_PROJECT_NAME}
#    env_file:
#      - .env
#    volumes:
#      - nginx-certificates:/geonode-certificates
#    restart: unless-stopped

  # Geoserver backend
  geoserver:
    image: ${COMPOSE_PROJECT_NAME}/geoserver:${GEOSERVER_BASE_IMAGE_VERSION}
    build:
      context: ./docker/geoserver
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE_VERSION=${GEOSERVER_BASE_IMAGE_VERSION}
    container_name: geoserver4${COMPOSE_PROJECT_NAME}
    healthcheck:
      test: "curl -m 10 --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null http://geoserver:8080/geoserver/ows"
      start_period: 60s
      interval: 60s
      timeout: 10s
      retries: 2
    env_file:
      - .env
    ports:
      - "8090:8080"
    volumes:
      - statics:/mnt/volumes/statics
      - geoserver-data-dir:/geoserver_data/data
      - backup-restore:/backup_restore
      - data:/data
      - tmp:/tmp
    restart: unless-stopped
    depends_on:
      data-dir-conf:
        condition: service_healthy
      django:
        condition: service_healthy

    networks:
      - default
      - global
    labels:
      - traefik.enable=true
      - traefik.http.routers.geoserver-stable.entrypoints=https
      - traefik.http.routers.geoserver-stable.rule=(Host(`${HTTP_HOST}`) && PathRegexp(`^\/(geoserver|geoserver\/.*)$`))
      - traefik.http.routers.geonode-stable.priority=999

      - traefik.http.routers.geoserver-stable.tls=true
      - traefik.http.services.geoserver-stable.loadbalancer.server.port=8080
      - traefik.docker.network=global

      # allowing cors:

      - traefik.http.middlewares.cors-header.headers.accesscontrolallowmethods=GET,POST,PUT,PATCH,DELETE,HEAD,OPTIONS
      - traefik.http.middlewares.cors-header.headers.accesscontrolallowheaders=*
      - traefik.http.middlewares.cors-header.headers.accesscontrolmaxage=10000
      - traefik.http.middlewares.cors-header.headers.addvaryheader=true

      - traefik.http.routers.geoserver-stable.middlewares=cors-header

  data-dir-conf:
    image: ${COMPOSE_PROJECT_NAME}/geoserver_data:${GEOSERVER_DATA_BASE_IMAGE_VERSION}
    build:
      context: ./docker/geoserver_data
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE_VERSION=${GEOSERVER_DATA_BASE_IMAGE_VERSION}
    container_name: gsconf4${COMPOSE_PROJECT_NAME}
    entrypoint: sleep infinity
    volumes:
      - geoserver-data-dir:/geoserver_data/data
    restart: unless-stopped
    healthcheck:
      test: "ls -A '/geoserver_data/data' | wc -l"

  # PostGIS database.
  db:
    image: ${COMPOSE_PROJECT_NAME}/postgis:${POSTGRES_BASE_IMAGE_VERSION}
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE_VERSION=${POSTGRES_BASE_IMAGE_VERSION}
    command: postgres -c "max_connections=${POSTGRESQL_MAX_CONNECTIONS}"
    container_name: db4${COMPOSE_PROJECT_NAME}
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
      - dbbackups:/pg_backups
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -d postgres -U postgres"
    # uncomment to enable remote connections to postgres
    #ports:
    #  - "5432:5432"

    networks:
      - global
      - default

    labels:
      - traefik.enable=true
      - traefik.tcp.routers.geonode-postgis.rule=HostSNI(`geonode-postgis.${DOMAIN}`)
      - traefik.tcp.routers.geonode-postgis.tls=true
      - traefik.tcp.routers.geonode-postgis.entrypoints=tcp
      - traefik.tcp.services.geonode-postgis.loadbalancer.server.port=5432
      - traefik.docker.network=global

  # Vanilla RabbitMQ service. This is needed by celery
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: rabbitmq4${COMPOSE_PROJECT_NAME}
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  statics:
    name: ${COMPOSE_PROJECT_NAME}-statics
  nginx-confd:
    name: ${COMPOSE_PROJECT_NAME}-nginxconfd
  nginx-certificates:
    name: ${COMPOSE_PROJECT_NAME}-nginxcerts
  geoserver-data-dir:
    name: ${COMPOSE_PROJECT_NAME}-gsdatadir
  dbdata:
    name: ${COMPOSE_PROJECT_NAME}-dbdata
  dbbackups:
    name: ${COMPOSE_PROJECT_NAME}-dbbackups
  backup-restore:
    name: ${COMPOSE_PROJECT_NAME}-backup-restore
  data:
    name: ${COMPOSE_PROJECT_NAME}-data
  tmp:
    name: ${COMPOSE_PROJECT_NAME}-tmp
  rabbitmq:
    name: ${COMPOSE_PROJECT_NAME}-rabbitmq
```

as well as my env file (everything I can remember modifying in the env file):

```env
COMPOSE_PROJECT_NAME=my_geonode
# See https://github.com/containers/podman/issues/13889
# DOCKER_BUILDKIT=0
DOCKER_ENV=production
# See https://github.com/geosolutions-it/geonode-generic/issues/28
# to see why we force API version to 1.24
DOCKER_API_VERSION="1.24"
BACKUPS_VOLUME_DRIVER=local

GEONODE_BASE_IMAGE_VERSION=4.4.x
NGINX_BASE_IMAGE_VERSION=1.25.3-latest
LETSENCRYPT_BASE_IMAGE_VERSION=2.6.0-latest
GEOSERVER_BASE_IMAGE_VERSION=2.24.4-v1
GEOSERVER_DATA_BASE_IMAGE_VERSION=2.24.4-v1
POSTGRES_BASE_IMAGE_VERSION=15.3-latest

DJANGO_SETTINGS_MODULE=my_geonode.settings
GEONODE_INSTANCE_NAME=geonode

DOMAIN=<your-domain.com>

SITEURL=https://geonode.${DOMAIN}/

# ALLOWED_HOSTS="['*', ]"
ALLOWED_HOSTS="['django', 'localhost', '*', 'geonode.${DOMAIN}', 'geoserver.${DOMAIN}']"

# #################
# nginx
# HTTPD Server
# #################
GEONODE_LB_HOST_IP=django
GEONODE_LB_PORT=8000
NGINX_BASE_URL=https://geonode.${DOMAIN}

# IP or domain name and port where the server can be reached on HTTPS (leave HOST empty if you want to use HTTP only)
# port where the server can be reached on HTTPS
HTTP_HOST=geonode.${DOMAIN}
HTTPS_HOST=geonode.${DOMAIN}

HTTP_PORT=13377
HTTPS_PORT=

LETSENCRYPT_MODE=disabled
# LETSENCRYPT_MODE=staging
# LETSENCRYPT_MODE=production

# #################
# geoserver
# #################
GEOSERVER_LB_HOST_IP=geoserver
GEOSERVER_LB_PORT=8080
GEOSERVER_WEB_UI_LOCATION=https://geonode.${DOMAIN}/geoserver/
GEOSERVER_PUBLIC_LOCATION=https://geonode.${DOMAIN}/geoserver/
GEOSERVER_LOCATION=http://${GEOSERVER_LB_HOST_IP}:${GEOSERVER_LB_PORT}/geoserver/

OGC_REQUEST_TIMEOUT=30
OGC_REQUEST_MAX_RETRIES=1
OGC_REQUEST_BACKOFF_FACTOR=0.3
OGC_REQUEST_POOL_MAXSIZE=10
OGC_REQUEST_POOL_CONNECTIONS=10

# Java Options & Memory
ENABLE_JSONP=true
outFormat=text/javascript
GEOSERVER_JAVA_OPTS=-Djava.awt.headless=true -Xms4G -Xmx4G -Dgwc.context.suffix=gwc -XX:+UnlockDiagnosticVMOptions -XX:+LogVMOutput -XX:LogFile=/var/log/jvm.log -XX:PerfDataSamplingInterval=500 -XX:SoftRefLRUPolicyMSPerMB=36000 -XX:-UseGCOverheadLimit -XX:ParallelGCThreads=4 -Dfile.encoding=UTF8 -Djavax.servlet.request.encoding=UTF-8 -Djavax.servlet.response.encoding=UTF-8 -Duser.timezone=GMT -Dorg.geotools.shapefile.datetime=false -DGS-SHAPEFILE-CHARSET=UTF-8 -DGEOSERVER_CSRF_DISABLED=true -DPRINT_BASE_URL=https://geonode.${DOMAIN}/geoserver/pdf -DALLOW_ENV_PARAMETRIZATION=true -Xbootclasspath/a:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/marlin-0.9.3-Unsafe.jar -Dsun.java2d.renderer=org.marlin.pisces.MarlinRenderingEngine

# Session/Access Control
LOCKDOWN_GEONODE=False
X_FRAME_OPTIONS="SAMEORIGIN"
SESSION_EXPIRED_CONTROL_ENABLED=True
DEFAULT_ANONYMOUS_VIEW_PERMISSION=True
DEFAULT_ANONYMOUS_DOWNLOAD_PERMISSION=True

CORS_ALLOW_ALL_ORIGINS=True
GEOSERVER_CORS_ENABLED=True
GEOSERVER_CORS_ALLOWED_ORIGINS=*
GEOSERVER_CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,HEAD,OPTIONS
GEOSERVER_CORS_ALLOWED_HEADERS=*

# #################
# Production and
# Monitoring
# #################
DEBUG=True

# PostgreSQL
POSTGRESQL_MAX_CONNECTIONS=200

DEFAULT_MAX_UPLOAD_SIZE=5368709120
DEFAULT_MAX_PARALLEL_UPLOADS_PER_USER=5
```
